# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180602_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 14, 36, 55, 529093, tzinfo=utc)),
        ),
    ]
